export const UPLOAD_COMPONENT_DEFINITION_REQUEST = "UPLOAD_COMPONENT_DEFINITION_REQUEST";
export const UPLOAD_COMPONENT_DEFINITION_SUCCESS = "UPLOAD_COMPONENT_DEFINITION_SUCCESS";
export const UPLOAD_COMPONENT_DEFINITION_FAILURE = "UPLOAD_COMPONENT_DEFINITION_FAILURE";

export const FETCH_COMPONENT_DEFINITION_REQUEST = "FETCH_COMPONENT_DEFINITION_REQUEST";
export const FETCH_COMPONENT_DEFINITION_SUCCESS = "FETCH_COMPONENT_DEFINITION_SUCCESS";
export const FETCH_COMPONENT_DEFINITION_FAILURE = "FETCH_COMPONENT_DEFINITION_FAILURE";

export const DELETE_COMPONENT_DEFINITION_REQUEST = "DELETE_COMPONENT_DEFINITION_REQUEST";
export const DELETE_COMPONENT_DEFINITION_SUCCESS = "DELETE_COMPONENT_DEFINITION_SUCCESS";
export const DELETE_COMPONENT_DEFINITION_FAILURE = "DELETE_COMPONENT_DEFINITION_FAILURE";

export const UPDATE_COMPONENT_DEFINITION_REQUEST = "UPDATE_COMPONENT_DEFINITION_REQUEST";
export const UPDATE_COMPONENT_DEFINITION_SUCCESS = "UPDATE_COMPONENT_DEFINITION_SUCCESS";
export const UPDATE_COMPONENT_DEFINITION_FAILURE = "UPDATE_COMPONENT_DEFINITION_FAILURE";

export const SUBMIT_EXPERIMENT_JSON_REQUEST = "SUBMIT_EXPERIMENT_JSON_REQUEST";
export const SUBMIT_EXPERIMENT_JSON_SUCCESS = "SUBMIT_EXPERIMENT_JSON_SUCCESS";
export const SUBMIT_EXPERIMENT_JSON_FAILURE = "SUBMIT_EXPERIMENT_JSON_FAILURE";

export const SUBMIT_COMPONENT_DEPENENCY_REQUEST = "SUBMIT_COMPONENT_DEPENENCY_REQUEST";
export const SUBMIT_COMPONENT_DEPENENCY_SUCCESS = "SUBMIT_COMPONENT_DEPENENCY_SUCCESS";
export const SUBMIT_COMPONENT_DEPENENCY_FAILURE = "SUBMIT_COMPONENT_DEPENENCY_FAILURE";

//ENVIRONMENT CONFIG
export const UPLOAD_ENVIRONMENT_CONFIG_REQUEST = "UPLOAD_ENVIRONMENT_CONFIG_REQUEST";
export const UPLOAD_ENVIRONMENT_CONFIG_SUCCESS = "UPLOAD_ENVIRONMENT_CONFIG_SUCCESS";
export const UPLOAD_ENVIRONMENT_CONFIG_FAILURE = "UPLOAD_ENVIRONMENT_CONFIG_FAILURE";

export const FETCH_ENVIRONMENT_CONFIG_REQUEST = "FETCH_ENVIRONMENT_CONFIG_REQUEST";
export const FETCH_ENVIRONMENT_CONFIG_SUCCESS = "FETCH_ENVIRONMENT_CONFIG_SUCCESS";
export const FETCH_ENVIRONMENT_CONFIG_FAILURE = "FETCH_ENVIRONMENT_CONFIG_FAILURE";

export const DELETE_ENVIRONMENT_CONFIG_REQUEST = "DELETE_ENVIRONMENT_CONFIG_REQUEST";
export const DELETE_ENVIRONMENT_CONFIG_SUCCESS = "DELETE_ENVIRONMENT_CONFIG_SUCCESS";
export const DELETE_ENVIRONMENT_CONFIG_FAILURE = "DELETE_ENVIRONMENT_CONFIG_FAILURE";

export const UPDATE_ENVIRONMENT_CONFIG_REQUEST = "UPDATE_ENVIRONMENT_CONFIG_REQUEST";
export const UPDATE_ENVIRONMENT_CONFIG_SUCCESS = "UPDATE_ENVIRONMENT_CONFIG_SUCCESS";
export const UPDATE_ENVIRONMENT_CONFIG_FAILURE = "UPDATE_ENVIRONMENT_CONFIG_FAILURE";
