export const UPLOAD_COMPONENT_DEFINITION_REQUEST = "UPLOAD_COMPONENT_DEFINITION_REQUEST";
export const UPLOAD_COMPONENT_DEFINITION_SUCCESS = "UPLOAD_COMPONENT_DEFINITION_SUCCESS";
export const UPLOAD_COMPONENT_DEFINITION_FAILURE = "UPLOAD_COMPONENT_DEFINITION_FAILURE";

export const FETCH_COMPONENT_DEFINITION_REQUEST = "FETCH_COMPONENT_DEFINITION_REQUEST";
export const FETCH_COMPONENT_DEFINITION_SUCCESS = "FETCH_COMPONENT_DEFINITION_SUCCESS";
export const FETCH_COMPONENT_DEFINITION_FAILURE = "FETCH_COMPONENT_DEFINITION_FAILURE";

export const DELETE_COMPONENT_DEFINITION_REQUEST = "FETCH_DELETE_DEFINITION_REQUEST";
export const DELETE_COMPONENT_DEFINITION_SUCCESS = "FETCH_DELETE_DEFINITION_SUCCESS";
export const DELETE_COMPONENT_DEFINITION_FAILURE = "FETCH_DELETE_DEFINITION_FAILURE";