export const UPLOAD_COMPONENT_DEFINITION_REQUEST = "UPLOAD_COMPONENT_DEFINITION_REQUEST";
export const UPLOAD_COMPONENT_DEFINITION_SUCCESS = "UPLOAD_COMPONENT_DEFINITION_SUCCESS";
export const UPLOAD_COMPONENT_DEFINITION_FAILURE = "UPLOAD_COMPONENT_DEFINITION_FAILURE";

export const FETCH_COMPONENT_DEFINITION_REQUEST = "FETCH_COMPONENT_DEFINITION_REQUEST";
export const FETCH_COMPONENT_DEFINITION_SUCCESS = "FETCH_COMPONENT_DEFINITION_SUCCESS";
export const FETCH_COMPONENT_DEFINITION_FAILURE = "FETCH_COMPONENT_DEFINITION_FAILURE";

export const DELETE_COMPONENT_DEFINITION_REQUEST = "DELETE_COMPONENT_DEFINITION_REQUEST";
export const DELETE_COMPONENT_DEFINITION_SUCCESS = "DELETE_COMPONENT_DEFINITION_SUCCESS";
export const DELETE_COMPONENT_DEFINITION_FAILURE = "DELETE_COMPONENT_DEFINITION_FAILURE";

export const UPDATE_COMPONENT_DEFINITION_REQUEST = "UPDATE_COMPONENT_DEFINITION_REQUEST";
export const UPDATE_COMPONENT_DEFINITION_SUCCESS = "UPDATE_COMPONENT_DEFINITION_SUCCESS";
export const UPDATE_COMPONENT_DEFINITION_FAILURE = "UPDATE_COMPONENT_DEFINITION_FAILURE";